### PR TITLE
Add new MOOC Reviews custom dataset

### PR DESCRIPTION
**Pull request by aparnavalli**

### CODE REVIEW

**Comment by yangheng95** [comment]
Thanks for your contribution, now your dataset is registered as 121.MOOC-En and available in PyABSA.

**Comment by yangheng95** [comment]
@aparnavalli

**Comment by yangheng95** [comment]
image
Here is the preliminary experiment result

**Comment by aparnavalli** [comment]
Its Working..Thanks

**Comment by yangheng95** [comment]
Hi @aparnavalli ,
I upload the augmented datasets which may help you.
Cheers!

**Comment by aparnavalli** [comment]
Hi.
Thank you for approving the custom dataset.

i'm trying to train the aspect extractor..getting this error..

[image: image.png]

Just want to check if this is causing any issue..


[image: image.png]
Should self.MOOC_En also be included in this list?
Thank you

**Comment by yangheng95** [comment]
Sorry, I can not access the pics, can you try uploading again?

**Pull request merged**
